// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SISTEMA_HOTEL.MODEL.Models;

public partial class Hospede
{
    [Key]
    public int HospedeId { get; set; }

    public string Nome { get; set; }

    public string Email { get; set; }

    public string Telefone { get; set; }

    public string DocumentoIdentificacao { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}