// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_HOTEL.MODEL.Models;

public partial class Quarto
{
    public int QuartoId { get; set; }

    public int Numero { get; set; }

    public string Tipo { get; set; }

    public decimal? Preco { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}