// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_HOTEL.MODEL.Models;

public partial class Reserva
{
    public int ReservaId { get; set; }

    public int? QuartoId { get; set; }

    public int? HospedeId { get; set; }

    public DateOnly DataCheckin { get; set; }

    public DateOnly DataCheckout { get; set; }

    public string Status { get; set; }

    public virtual Hospede Hospede { get; set; }

    public virtual Quarto Quarto { get; set; }
}